# Generated by Django 4.0.3 on 2022-04-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(null=True, upload_to='slider'),
        ),
    ]
