# Generated by Django 4.0.3 on 2022-04-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0004_about_aboutbrief_aboutprojects_aboutskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutprojects',
            name='counts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aboutskill',
            name='counts',
            field=models.IntegerField(),
        ),
    ]
