# Generated by Django 4.0.3 on 2022-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0007_experience_experiencelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencelist',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
